/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interfaces;

import Classes.Reservation;
import DataStructures.Node;
import FunctionalitiesSoftware.FindReservation;
import javax.swing.JOptionPane;

/**
 *
 * @author gigie
 */
public class ReservationSearch extends javax.swing.JFrame {

    /**
     * Creates new form ReservationSearch
     */
    public ReservationSearch() {
        initComponents();
        this.setVisible(true);
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        IdClient = new javax.swing.JTextField();
        GoBackReservationSearch = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        SearchReservationById = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Búsqueda de Reservación");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 40, -1, -1));

        jLabel2.setText("Ingrese la cédula del cliente:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, -1, -1));

        IdClient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IdClientActionPerformed(evt);
            }
        });
        jPanel1.add(IdClient, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 110, 130, -1));

        GoBackReservationSearch.setText("Regresar al menú principal");
        GoBackReservationSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GoBackReservationSearchActionPerformed(evt);
            }
        });
        jPanel1.add(GoBackReservationSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 220, -1, -1));

        jButton6.setText("X");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 10, -1, -1));

        SearchReservationById.setText("Buscar");
        SearchReservationById.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchReservationByIdActionPerformed(evt);
            }
        });
        jPanel1.add(SearchReservationById, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 170, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 300));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jButton6ActionPerformed

    private void GoBackReservationSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GoBackReservationSearchActionPerformed
        Menu menu = new Menu();
        menu.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_GoBackReservationSearchActionPerformed

    private void SearchReservationByIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchReservationByIdActionPerformed
        try {
            String id = IdClient.getText();
            int idnum = Integer.parseInt(id);
            FindReservation fr = new FindReservation();
            Node reservation1 = fr.getReservationByClientId(idnum);
            if (reservation1 == null) {
                JOptionPane.showMessageDialog(rootPane, "No existe una reservación con esa cédula");
            } else {
                String idNumber = Integer.toString(reservation1.getId());
                Reservation reservationWanted = (Reservation) reservation1.getData();
                String firstName = reservationWanted.getClientFirstName();
                String lastName = reservationWanted.getClientLastName();
                String email = reservationWanted.getClientEmail();
                String gender = reservationWanted.getClientGender();
                String typeOfRoom = reservationWanted.getTypeOfRoom();
                String phoneNumber = reservationWanted.getClientPhone();
                String dateOfArrival = reservationWanted.getDateOfArrival();
                String dateOfDeparture = reservationWanted.getDateOfDeparture();

                JOptionPane.showMessageDialog(rootPane, "Cédula: " + idNumber + "\nNombre: " + firstName + "\nApellido: " + lastName + "\nEmail: " + email + "\nGénero: " + gender + "\nTipo de habitación: " + typeOfRoom + "\nNúmero de teléfono: " + phoneNumber + "\nFecha de llegada: " + dateOfArrival + "\nFecha de salida: " + dateOfDeparture);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, "La cédula es un número. Solo puede ingresar caracteres que sean números");

        }
    }//GEN-LAST:event_SearchReservationByIdActionPerformed

    private void IdClientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IdClientActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_IdClientActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ReservationSearch.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ReservationSearch.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ReservationSearch.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ReservationSearch.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ReservationSearch().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton GoBackReservationSearch;
    private javax.swing.JTextField IdClient;
    private javax.swing.JButton SearchReservationById;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
