/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interfaces;

import Classes.HashTable;
import Classes.Reservation;
import DataStructures.List;
import DataStructures.Node;
import DataStructures.Tree;
import FunctionalitiesSoftware.Checkout;
import FunctionalitiesSoftware.FindReservation;
import static Interfaces.ReservationSearch.hashTable;
import static Interfaces.ReservationSearch.historyTree;
import static Interfaces.ReservationSearch.reservationsTree;
import static Interfaces.ReservationSearch.roomsTree;
import javax.swing.JOptionPane;

/**
 *
 * @author gigie
 */
public class CheckOut extends javax.swing.JFrame {
    public static Tree reservationsTree;
    public static Tree roomsTree;
    public static Tree historyTree;
    public static HashTable hashTable;
    /**
     * Creates new form CheckOut
     */
    public CheckOut(Tree reservationsTree, Tree roomsTree, Tree historyTree, HashTable hashTable) {
        this.reservationsTree = reservationsTree;
        this.roomsTree = roomsTree;
        this.historyTree = historyTree;
        this.hashTable = hashTable;
        initComponents();
        this.setVisible(true);
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        GoBackCheckOut = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        Name = new javax.swing.JTextField();
        LName = new javax.swing.JTextField();
        ID = new javax.swing.JTextField();
        jButton6 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        GoBackCheckOut.setText("Regresar al menú principal");
        GoBackCheckOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GoBackCheckOutActionPerformed(evt);
            }
        });
        jPanel1.add(GoBackCheckOut, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 240, -1, -1));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Check-Out");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 40, -1, -1));

        jLabel2.setText("Nombre");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 90, -1, -1));

        jLabel3.setText("Apellido");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 120, -1, -1));

        jLabel4.setText("Cédula");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 150, -1, -1));

        Name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NameActionPerformed(evt);
            }
        });
        jPanel1.add(Name, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 90, 210, -1));

        LName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LNameActionPerformed(evt);
            }
        });
        jPanel1.add(LName, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 120, 210, -1));
        jPanel1.add(ID, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 150, 210, -1));

        jButton6.setText("X");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 10, -1, -1));

        jButton2.setText("Cerrar Registro");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 200, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 300));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void NameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NameActionPerformed

    private void LNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_LNameActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jButton6ActionPerformed

    private void GoBackCheckOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GoBackCheckOutActionPerformed
        Menu menu = new Menu(reservationsTree,  roomsTree,  historyTree,  hashTable);
        menu.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_GoBackCheckOutActionPerformed

    public String capitalizeFirstLetter(String input) {
        if (input == null || input.isEmpty()) {
            return input; // Si el string es nulo o vacío, devolverlo sin cambios
        } else {
            return input.substring(0, 1).toUpperCase() + input.substring(1); // Capitalizar la primera letra y concatenar el resto del string
        }
    }
    
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        
        try {
            
            String name1 = Name.getText().trim().toLowerCase();
            String lastName1 = LName.getText().trim().toLowerCase();
            String name = capitalizeFirstLetter(name1);
            String lastName = capitalizeFirstLetter(lastName1);
            
            String id = ID.getText();
            int idnum = Integer.parseInt(id);
            FindReservation fr = new FindReservation();
            
            Node reservation1 = fr.getReservationByClientId(idnum, reservationsTree);
         
            
            
            // Verificar si el nombre no es un String válido
            if (!name.matches("[\\p{L}]+") || !lastName.matches("[\\p{L}]+")) {
                if (!name.matches("[\\p{L}]+")) {
                    JOptionPane.showMessageDialog(rootPane, "El nombre solo puede contener letras");

                }

                // Verificar si el apellido no es un String válido
                if (!lastName.matches("[\\p{L}]+")) {
                    JOptionPane.showMessageDialog(rootPane, "El apellido solo puede contener letras");

                }
                //Integer.valueOf(ID);
                
                
            }
           
            if (reservation1 == null) {
                JOptionPane.showMessageDialog(rootPane, "No existe una reservación con esa cédula");
            }       
            
            else{
                Reservation reservationWanted = (Reservation) reservation1.getData();
                
                
                Checkout checkO = new Checkout(hashTable, roomsTree, reservationsTree, historyTree);
                
                JOptionPane.showMessageDialog(rootPane, checkO.Checkoutci(idnum, reservation1));
                
               
            }
           
         }catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Debe ingresar un numero de cedula valido, sin puntos ni comas.");
            
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CheckOut.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CheckOut.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CheckOut.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CheckOut.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CheckOut( reservationsTree,  roomsTree,  historyTree,  hashTable).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton GoBackCheckOut;
    private javax.swing.JTextField ID;
    private javax.swing.JTextField LName;
    private javax.swing.JTextField Name;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
